name: slack-pr-integration-action
on:
  pull_request_target:
    types: [opened, labeled, reopened ]
jobs:
  do-slack-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: RevathiKotla/slack-pr-integration-action@v1
        name: jira-description-action
        env:
          SLACK_WEBHOOK_URL : ${{ secrets.SLACK_WEBHOOK_URL }}
          PULL_REQUEST_NUMBER : ${{ github.event.pull_request.number }}
          PULL_REQUEST_TITLE : ${{ github.event.pull_request.title }}
